services:
  app:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - FLASK_APP=manage.py
      - DATABASE_URL=postgresql://${USERNAME}:${PASSWORD}@${HOSTNAME}:5432/${NAME}
    command: ./run.sh
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:14.18
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERNAME} -d ${NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
