{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tinycloud-backend.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tinycloud-backend.name" . }}
    {{- include "tinycloud-backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
