eck-elasticsearch:
  enabled: true
  fullnameOverride: elasticsearch-tinycloud
  spec:
    version: 8.12.0
  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
      volumeClaimTemplate:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClass: gp3
            resources:
              requests:
                storage: 20Gi
