apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Release.Name }}-init-db
          image: tinycloud-app:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: database
            - name: POSTGRES_HOST
              value: postgresql
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              while ! timeout 1 bash -c 'cat < /dev/null > /dev/tcp/postgresql/5432'; do
                sleep 2
              done
              echo "PostgreSQL is ready"
              echo "Initializing database..."
              flask db upgrade
              echo "Database initialized"
      restartPolicy: Never
  backoffLimit: 0
