apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: {{ .Values.storage.type }}
    fsType: {{ .Values.storage.fsType }}
    encrypted: "true"
  allowVolumeExpansion: true