database:
  enabled: true
  type: postgresql
  storage:
    type: "emptyDir"
    pvc:
      size: 1Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce

postgresql:
  enabled: true
  username: ""
  password: ""
  database: tinycloud
  host: tinycloud-postgresql


env:
  FLASK_ENV: production

# Storage class

type: gp2
fsType: ext4