postgresql:
  name: "postgresql"
  username: ""
  password: ""
  database: ""
  host: ""
  port: ""
  protocol: "TCP"
  storage:
    type: "emptyDir"
    pvc:
      size: 1Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15"

resources:
  limits:
      cpu: 500m
      memory: 512Mi
  requests:
      cpu: 100m
      memory: 256Mi

secretName: "postgresql-dev-secret"

env:
  FLASK_ENV: dev

# Storage class

type: gp2
fsType: ext4

tolerations:
  - key: "environment"
    operator: "Equal"
    value: "dev"
    effect: "NoSchedule"

nodeSelector:
  environment: "dev"