postgresql:
  name: ""
  username: ""
  password: ""
  database: ""
  host: ""
  port: ""
  protocol: ""
  storage:
    type: ""
    pvc:
      size: ""
      storageClass: ""
      accessModes: []

resources: {}

secretName: ""

env:
  FLASK_ENV: ""

# Storage class

type: ""
fsType: ""